[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false
clear_limit = 50

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
type = "CosmosSdk"
id = "sei"
rpc_addr = "http://127.0.0.1:27657/"
grpc_addr = "http://127.0.0.1:9190/"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "sei"
key_name = ""
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 2.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
allow_ccq = true
compat_mode = '0.37'

[chains.event_source]
mode = "pull"
interval = "50ms"
max_retries = 4

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.02
denom = "usei"

[chains.dynamic_gas_price]
enabled = false
multiplier = 1.1
max = 0.6

[chains.address_type]
derivation = "cosmos"

[[chains]]
type = "CosmosSdk"
id = "localcosmos-1"
rpc_addr = "http://127.0.0.1:28657/"
grpc_addr = "http://127.0.0.1:9290/"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cosmos"
key_name = ""
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 2.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
allow_ccq = true

[chains.event_source]
mode = "pull"
interval = "500ms"
max_retries = 4

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "uatom"

[chains.dynamic_gas_price]
enabled = false
multiplier = 1.1
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[tracing_server]
enabled = false
port = 5555

